---
version: '2.4'
services:
  voting-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "${PORT}:${PORT}"
    env_file: ./.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    entrypoint: npm start
